os: windows
language: sh
python: '3.7'
before_install:
- choco install python3
- export PATH="/C/Python37:/C/Python37/Scripts:$PATH"
install:
- python -m pip install -r requirements.txt
cache:
  directories:
  - /C/Python37
  - $HOME/AppData/Roaming/Python/Python37
before_cache:
  - find /C/Python37/Lib/ -name '*.pyc' -delete
script: python -m pytest --cache-clear tests
before_deploy: pyinstaller --name AbsorptionImaging-$TRAVIS_TAG-win64 --onefile --noconsole __main__.py
deploy:
  provider: releases
  api_key:
    secure: evkdhNgbkI7j6lXrNG1HuFhOj4HcF0UF9EtD1Z017AFR1yw/CaoylTqbJX6dA+ZsEz4j+4LFC2gGm0Qkz1MaX3NBUIqrHw/vVikWSA/Rp/5Zhd/51S15AXPEiQbPqlfdppUki53WAFWPIYOvRNr0niZKUj/juY5S7ElMOxGq+4FOBcHH3C445uYbDtStHCUiwZ/V6CqzRWoOgayP7qs6SN/HheNURKbKIrjKsD+dxgAjQ29et/LDZ/WMYILHK4+CbTpIneuvrDgvDnbyfDl6ARlzXbEQXTcUeIREyR9v6lJSUxsTbh5UKERpZo83GEFSVsyyCnV4J+joFrpLKxi3uyxlzS5IUARM9FZ81dT2kmP3QPPdnmRhs4AuRD4zy8+LLAv/sJ6xnIF880J6kY10L5tVCwveN5keixedwYwMTo09yGAriPpwMWGqPtIAFcY3L6HU9UtRhmLJQj6ZGhvRf8Sehd05fmJbH5zeAnUV8uFPUOnrxP6i6CCosCpFboPbX0M1g24YmoLYt542kaXKbRDyAOpXBFpcSuJ1jCMdbu1Nk/DRsWQuS9uC8gyN1XOkyqG2aJcmf6ZNQGxflMr3UHZlEtxE2Z8OrdvXAU0qZ0w1/fq/BM/faAQLyL9+m30a7ZjLYG8yJg0sZOIZ9pvuZ+/8V5jCPZLGKbAIQrpSjD4=
  file_glob: true
  file: dist/*.exe
  skip_cleanup: true
  name: $TRAVIS_TAG
  draft: true
  on:
    tags: true
