os: windows
language: sh
python: '3.7'
before_install:
- choco install python3 --version=3.7.5
- export PATH="/C/Python37:/C/Python37/Scripts:$PATH"
install:
- python -m pip install -r requirements.txt
cache:
  directories:
  - /C/Python37
  - $HOME/AppData/Roaming/Python/Python37
before_cache:
  - find /C/Python37/Lib/ -name '*.pyc' -delete
script: python -m pytest --cache-clear tests
before_deploy: pyinstaller --name AbsorptionImaging-$TRAVIS_TAG-win64 --onefile --noconsole __main__.py
deploy:
  provider: releases
  api_key:
    secure: ktwEhXT9nMNUiGp6bIZ24A3GkWdpiLGqWMFY+1LF9OkxnC8BNMD0crwMy+5TFr0F2EVyhx+l38gy0dY4pxfX0tn70LHt1yHMBdN9cYBPezzjCW2JCt6JFRT7vcmFs4YoWLYXHe+HfAWPZyt3aHtJWqpib0c92dUW7DHMZz3K5UJIYE1VthGv/WhWz98KpQNQJeuTG4fsDmLVvyPqZavu5n+MehDsI6fhneP8aE0DPWHcQiOpQAZUG0p2GemTkd1bdobz4Pd0TMo85lbGx3HScEZ8qpptEL95DIhYkYz9qgMO9adpr9FsKeyeRx1ELRkSxu0RFNISsrBKFh7c7Yoklb4HzaBpFjG+YisUy0Mc5SpPJeRjHJPI1hlopqrwMMEQdqe3w+fxzD5VatoH8WgVqX5W72C9NjgHEYZ7pi2m9UjGPoux0TAVxPmyZxHgSGYOs+by/MZ8BFlw5i4jUFL3rdEILf7aa+tqeaWrT+v14rlyEPuK1uP369kfPQUFSwZ3P1Jdj5qYZwsKySZj+gK/owChE77eufzEQDMrKkCUVVh5uIeE3Jec51tmr2B5TvHhAVx+ZiCu050HhCE2938w9v25f8NXmTYCxweKpo010UMENfmmv4Tvw4MMFmBgbF0tyFcOBLqtTiZPiz4CO+VTFRYtqGTS4SGO4aYgS2y0bpM=
  file_glob: true
  file: dist/*.exe
  skip_cleanup: true
  name: $TRAVIS_TAG
  draft: true
  on:
    tags: true
